-- pg_trgm 拡張（日本語同一視・部分一致検索用）
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 1. アカウント管理 (LOGIN_ACCOUNT)
CREATE TABLE IF NOT EXISTS LOGIN_ACCOUNT (
    USER_ID VARCHAR(36) PRIMARY KEY,
    USER_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(320) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_AT TIMESTAMPTZ,
    LOGIN_FAILED_COUNT INT NOT NULL DEFAULT 0,
    LOGIN_LAST_FAILED_AT TIMESTAMPTZ,
    LOGIN_LOCK_UNTIL TIMESTAMPTZ,
    REAUTH_FAILED_COUNT INT NOT NULL DEFAULT 0,
    REAUTH_LAST_FAILED_AT TIMESTAMPTZ,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    UPDATED_AT TIMESTAMPTZ NOT NULL
);

-- 2. タスク管理 (TASK)
CREATE TABLE IF NOT EXISTS TASK (
    TASK_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL REFERENCES LOGIN_ACCOUNT(USER_ID) ON DELETE CASCADE,
    TITLE VARCHAR(255) NOT NULL,
    PRIORITY VARCHAR(20) NOT NULL DEFAULT 'medium',
    DUE_DATETIME TIMESTAMPTZ,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'not_started',
    IS_PINNED BOOLEAN NOT NULL DEFAULT FALSE,
    COMMENT TEXT NOT NULL DEFAULT '',
    SEARCH_TEXT TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    UPDATED_AT TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_task_priority CHECK (PRIORITY IN ('low', 'medium', 'high')),
    CONSTRAINT chk_task_status CHECK (STATUS IN ('not_started', 'in_progress', 'completed'))
);

-- 3. ログインセッション管理 (LOGIN_SESSION)
CREATE TABLE IF NOT EXISTS LOGIN_SESSION (
    SESSION_ID VARCHAR(64) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL REFERENCES LOGIN_ACCOUNT(USER_ID) ON DELETE CASCADE,
    EXPIRES_AT TIMESTAMPTZ NOT NULL,
    USER_AGENT TEXT,
    CREATED_AT TIMESTAMPTZ NOT NULL
);

-- 4. OTPセッション管理 (OTP_SESSION)
CREATE TABLE IF NOT EXISTS OTP_SESSION (
    OTP_SESSION_ID VARCHAR(64) PRIMARY KEY,
    PURPOSE VARCHAR(20) NOT NULL,
    USER_ID VARCHAR(36) REFERENCES LOGIN_ACCOUNT(USER_ID) ON DELETE CASCADE,
    PENDING_USERNAME VARCHAR(20),
    PENDING_EMAIL VARCHAR(255),
    MASKED_EMAIL VARCHAR(320) NOT NULL,
    PENDING_PASSWORD_HASH VARCHAR(255),
    OTP_HASH VARCHAR(255),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'active',
    IS_DUMMY BOOLEAN NOT NULL DEFAULT FALSE,
    ATTEMPT_COUNT INT NOT NULL DEFAULT 0,
    SEND_COUNT INT NOT NULL DEFAULT 0,
    SEND_FAILED_COUNT INT NOT NULL DEFAULT 0,
    DELIVERY_STATUS VARCHAR(20) NOT NULL DEFAULT 'pending',
    LAST_SENT_AT TIMESTAMPTZ NOT NULL,
    OTP_EXPIRES_AT TIMESTAMPTZ NOT NULL,
    SESSION_EXPIRES_AT TIMESTAMPTZ NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_otp_session_purpose CHECK (PURPOSE IN ('SIGNUP', 'PASSWORD_RESET', 'EMAIL_CHANGE')),
    CONSTRAINT chk_otp_session_status CHECK (STATUS IN ('active', 'verified')),
    CONSTRAINT chk_otp_session_real_required_values CHECK (IS_DUMMY OR (PENDING_EMAIL IS NOT NULL AND OTP_HASH IS NOT NULL)),
    CONSTRAINT chk_otp_session_signup_required_values CHECK (PURPOSE <> 'SIGNUP' OR IS_DUMMY OR (PENDING_USERNAME IS NOT NULL AND PENDING_PASSWORD_HASH IS NOT NULL)),
    CONSTRAINT chk_otp_session_email_change_owner CHECK (PURPOSE <> 'EMAIL_CHANGE' OR USER_ID IS NOT NULL),
    CONSTRAINT chk_otp_session_delivery_status CHECK (DELIVERY_STATUS IN ('pending', 'sent', 'sendable')),
    CONSTRAINT chk_otp_session_send_failed_count CHECK (SEND_FAILED_COUNT BETWEEN 0 AND 5)
);

-- 5. ログインレートリミット管理 (LOGIN_IP_RATE_LIMIT)
CREATE TABLE IF NOT EXISTS LOGIN_IP_RATE_LIMIT (
    IP_ADDRESS VARCHAR(45) PRIMARY KEY,
    FAILED_COUNT INT NOT NULL DEFAULT 0,
    LAST_FAILED_AT TIMESTAMPTZ NOT NULL,
    BLOCKED_UNTIL TIMESTAMPTZ,
    UPDATED_AT TIMESTAMPTZ NOT NULL
);

-- 6. ログ管理
-- 6.1 ログイン情報ログ (LOGIN_LOG)
CREATE TABLE IF NOT EXISTS LOGIN_LOG (
    LOG_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36),
    EMAIL VARCHAR(320) NOT NULL,
    IP_ADDRESS VARCHAR(45) NOT NULL,
    IS_SUCCESS BOOLEAN NOT NULL,
    IS_SESSION_USED BOOLEAN NOT NULL,
    ACCESS_AT TIMESTAMPTZ NOT NULL
);

-- 6.2 APIアクセスログ (ACCESS_LOG)
CREATE TABLE IF NOT EXISTS ACCESS_LOG (
    LOG_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36),
    IP_ADDRESS VARCHAR(45) NOT NULL,
    ENDPOINT VARCHAR(1000) NOT NULL,
    RESOURCE_ID VARCHAR(255),
    ACCESS_AT TIMESTAMPTZ NOT NULL
);

-- 6.3 メール認証ログ (MAIL_AUTH_LOG)
CREATE TABLE IF NOT EXISTS MAIL_AUTH_LOG (
    LOG_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36),
    EMAIL VARCHAR(320) NOT NULL,
    AUTH_TYPE VARCHAR(20) NOT NULL,
    IP_ADDRESS VARCHAR(45) NOT NULL,
    EVENT_TYPE VARCHAR(30) NOT NULL,
    IS_SUCCESS BOOLEAN NOT NULL,
    IS_DUMMY BOOLEAN NOT NULL,
    ACCESS_AT TIMESTAMPTZ NOT NULL
);

-- 7. インデックス
-- 7.1 TASK インデックス
CREATE INDEX IF NOT EXISTS idx_task_search_text ON TASK USING gin (SEARCH_TEXT gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_task_user_status_sort ON TASK (USER_ID, STATUS, IS_PINNED DESC, DUE_DATETIME ASC NULLS LAST, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS idx_task_user_sort ON TASK (USER_ID, IS_PINNED DESC, DUE_DATETIME ASC NULLS LAST, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS idx_task_user_due_datetime ON TASK (USER_ID, DUE_DATETIME);

-- 7.2 LOGIN_SESSION / OTP_SESSION インデックス
CREATE INDEX IF NOT EXISTS idx_login_session_user ON LOGIN_SESSION (USER_ID);
CREATE INDEX IF NOT EXISTS idx_login_session_expires ON LOGIN_SESSION (EXPIRES_AT);
CREATE UNIQUE INDEX IF NOT EXISTS uq_otp_session_active_pending_email ON OTP_SESSION (PENDING_EMAIL) WHERE STATUS IN ('active', 'verified');
CREATE INDEX IF NOT EXISTS idx_otp_session_pending_email ON OTP_SESSION (PENDING_EMAIL, STATUS, OTP_EXPIRES_AT);
CREATE INDEX IF NOT EXISTS idx_otp_session_session_expires ON OTP_SESSION (SESSION_EXPIRES_AT);
CREATE INDEX IF NOT EXISTS idx_otp_session_active_otp_expires ON OTP_SESSION (STATUS, OTP_EXPIRES_AT) WHERE STATUS = 'active';

-- 7.3 LOGIN_IP_RATE_LIMIT インデックス
CREATE INDEX IF NOT EXISTS idx_login_ip_rate_limit_purge ON LOGIN_IP_RATE_LIMIT (BLOCKED_UNTIL, LAST_FAILED_AT);

-- 7.4 ログテーブル インデックス
CREATE INDEX IF NOT EXISTS idx_login_log_ip ON LOGIN_LOG (IP_ADDRESS, ACCESS_AT DESC);
CREATE INDEX IF NOT EXISTS idx_login_log_email ON LOGIN_LOG (EMAIL, ACCESS_AT DESC);
CREATE INDEX IF NOT EXISTS idx_login_log_purge ON LOGIN_LOG (ACCESS_AT);

CREATE INDEX IF NOT EXISTS idx_access_log_purge ON ACCESS_LOG (ACCESS_AT);

CREATE INDEX IF NOT EXISTS idx_mail_auth_log_email ON MAIL_AUTH_LOG (EMAIL, ACCESS_AT DESC);
CREATE INDEX IF NOT EXISTS idx_mail_auth_log_purge ON MAIL_AUTH_LOG (ACCESS_AT);
