DROP TABLE IF EXISTS MAIL_AUTH_LOG CASCADE;
DROP TABLE IF EXISTS ACCESS_LOG CASCADE;
DROP TABLE IF EXISTS LOGIN_LOG CASCADE;
DROP TABLE IF EXISTS LOGIN_IP_RATE_LIMIT CASCADE;
DROP TABLE IF EXISTS OTP_SESSION CASCADE;
DROP TABLE IF EXISTS LOGIN_SESSION CASCADE;
DROP TABLE IF EXISTS TASK CASCADE;
DROP TABLE IF EXISTS LOGIN_ACCOUNT CASCADE;
DROP EXTENSION IF EXISTS pg_trgm;
